// Categories data for seeding
export const rootCategories = [
  { name: "Components", slug: "components", description: "PC components and hardware parts", displayOrder: 1, isFeatured: true },
  { name: "Peripherals", slug: "peripherals", description: "Keyboards, mice, monitors and accessories", displayOrder: 2, isFeatured: true },
  { name: "Laptops", slug: "laptops", description: "Gaming, business and everyday laptops", displayOrder: 3, isFeatured: true },
  { name: "Networking", slug: "networking", description: "Routers, switches, cables and networking", displayOrder: 4 },
  { name: "Storage", slug: "storage", description: "SSDs, HDDs, external drives", displayOrder: 5, isFeatured: true },
  { name: "Software", slug: "software", description: "Operating systems and software licenses", displayOrder: 6 },
  { name: "Gaming", slug: "gaming", description: "Gaming chairs, desks and accessories", displayOrder: 7, isFeatured: true },
  { name: "Office", slug: "office", description: "Office equipment and furniture", displayOrder: 8 },
  { name: "Printers", slug: "printers", description: "Printers, scanners and consumables", displayOrder: 9 },
  { name: "Audio", slug: "audio", description: "Speakers, headphones and audio equipment", displayOrder: 10 },
  { name: "Mobile Accessories", slug: "mobile-accessories", description: "Phone cases, chargers, cables", displayOrder: 11 },
  { name: "Smart Home", slug: "smart-home", description: "Smart devices and home automation", displayOrder: 12 },
];

export const subCategories: Record<string, Array<{ name: string; slug: string; displayOrder: number }>> = {
  components: [
    { name: "Processors", slug: "processors", displayOrder: 1 },
    { name: "Graphics Cards", slug: "graphics-cards", displayOrder: 2 },
    { name: "Motherboards", slug: "motherboards", displayOrder: 3 },
    { name: "RAM", slug: "ram", displayOrder: 4 },
    { name: "Power Supplies", slug: "power-supplies", displayOrder: 5 },
    { name: "PC Cases", slug: "pc-cases", displayOrder: 6 },
    { name: "CPU Coolers", slug: "cpu-coolers", displayOrder: 7 },
    { name: "Case Fans", slug: "case-fans", displayOrder: 8 },
    { name: "Thermal Paste", slug: "thermal-paste", displayOrder: 9 },
  ],
  peripherals: [
    { name: "Keyboards", slug: "keyboards", displayOrder: 1 },
    { name: "Mice", slug: "mice", displayOrder: 2 },
    { name: "Mouse Pads", slug: "mouse-pads", displayOrder: 3 },
    { name: "Monitors", slug: "monitors", displayOrder: 4 },
    { name: "Webcams", slug: "webcams", displayOrder: 5 },
    { name: "USB Hubs", slug: "usb-hubs", displayOrder: 6 },
    { name: "Cables & Adapters", slug: "cables-adapters", displayOrder: 7 },
  ],
  laptops: [
    { name: "Gaming Laptops", slug: "gaming-laptops", displayOrder: 1 },
    { name: "Business Laptops", slug: "business-laptops", displayOrder: 2 },
    { name: "Student Laptops", slug: "student-laptops", displayOrder: 3 },
    { name: "Thin & Light", slug: "thin-light-laptops", displayOrder: 4 },
    { name: "Workstation Laptops", slug: "workstation-laptops", displayOrder: 5 },
  ],
  storage: [
    { name: "Internal SSD", slug: "internal-ssd", displayOrder: 1 },
    { name: "Internal HDD", slug: "internal-hdd", displayOrder: 2 },
    { name: "NVMe SSD", slug: "nvme-ssd", displayOrder: 3 },
    { name: "External HDD", slug: "external-hdd", displayOrder: 4 },
    { name: "Pen Drives", slug: "pen-drives", displayOrder: 5 },
    { name: "Memory Cards", slug: "memory-cards", displayOrder: 6 },
  ],
  networking: [
    { name: "Routers", slug: "routers", displayOrder: 1 },
    { name: "Switches", slug: "switches", displayOrder: 2 },
    { name: "Network Cards", slug: "network-cards", displayOrder: 3 },
    { name: "Ethernet Cables", slug: "ethernet-cables", displayOrder: 4 },
    { name: "WiFi Adapters", slug: "wifi-adapters", displayOrder: 5 },
  ],
  audio: [
    { name: "Headphones", slug: "headphones", displayOrder: 1 },
    { name: "Earphones", slug: "earphones", displayOrder: 2 },
    { name: "Speakers", slug: "speakers", displayOrder: 3 },
    { name: "Microphones", slug: "microphones", displayOrder: 4 },
    { name: "Sound Cards", slug: "sound-cards", displayOrder: 5 },
  ],
  gaming: [
    { name: "Gaming Chairs", slug: "gaming-chairs", displayOrder: 1 },
    { name: "Gaming Desks", slug: "gaming-desks", displayOrder: 2 },
    { name: "Controllers", slug: "controllers", displayOrder: 3 },
    { name: "Gaming Headsets", slug: "gaming-headsets", displayOrder: 4 },
    { name: "Streaming Gear", slug: "streaming-gear", displayOrder: 5 },
  ],
  office: [
    { name: "Office Chairs", slug: "office-chairs", displayOrder: 1 },
    { name: "Desks", slug: "desks", displayOrder: 2 },
    { name: "UPS", slug: "ups", displayOrder: 3 },
    { name: "Surge Protectors", slug: "surge-protectors", displayOrder: 4 },
    { name: "Laptop Stands", slug: "laptop-stands", displayOrder: 5 },
  ],
  printers: [
    { name: "Inkjet Printers", slug: "inkjet-printers", displayOrder: 1 },
    { name: "Laser Printers", slug: "laser-printers", displayOrder: 2 },
    { name: "All-in-One Printers", slug: "all-in-one-printers", displayOrder: 3 },
    { name: "Ink & Toner", slug: "ink-toner", displayOrder: 4 },
    { name: "Scanners", slug: "scanners", displayOrder: 5 },
  ],
  software: [
    { name: "Operating Systems", slug: "operating-systems", displayOrder: 1 },
    { name: "Antivirus", slug: "antivirus", displayOrder: 2 },
    { name: "Office Suite", slug: "office-suite", displayOrder: 3 },
    { name: "Design Software", slug: "design-software", displayOrder: 4 },
  ],
  "mobile-accessories": [
    { name: "Phone Cases", slug: "phone-cases", displayOrder: 1 },
    { name: "Chargers", slug: "chargers", displayOrder: 2 },
    { name: "Power Banks", slug: "power-banks", displayOrder: 3 },
    { name: "Phone Stands", slug: "phone-stands", displayOrder: 4 },
  ],
  "smart-home": [
    { name: "Smart Lights", slug: "smart-lights", displayOrder: 1 },
    { name: "Smart Plugs", slug: "smart-plugs", displayOrder: 2 },
    { name: "Security Cameras", slug: "security-cameras", displayOrder: 3 },
  ],
};
