// Prebuilt PCs data for seeding - 20 prebuilt configurations

export interface PrebuiltPCData {
  name: string;
  slug: string;
  shortDescription: string;
  description: string;
  totalPrice: number;
  sellingPrice: number;
  compareAtPrice?: number;
  pcType: string;
  targetUse: string;
  isFeatured?: boolean;
  isComingSoon?: boolean;
  launchDate?: Date;
  tags?: string[];
  badges?: string[];
  components: Array<{
    productSlug: string;
    componentType: string;
    quantity: number;
  }>;
}

export const prebuiltPCs: PrebuiltPCData[] = [
  // ==================== GAMING PCs ====================
  {
    name: "SCB Destroyer RTX 4090",
    slug: "scb-destroyer-rtx-4090",
    shortDescription: "Ultimate 4K Gaming Beast with RTX 4090",
    description: "The most powerful gaming PC for 4K gaming at max settings. Featuring the flagship RTX 4090 and Intel i9 processor for uncompromising performance.",
    totalPrice: 350000,
    sellingPrice: 324999,
    compareAtPrice: 359999,
    pcType: "gaming-pc",
    targetUse: "4K Gaming, Streaming, Content Creation",
    isFeatured: true,
    tags: ["gaming", "premium", "4k"],
    badges: ["premium", "best-seller"],
    components: [
      { productSlug: "intel-core-i9-14900k", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4090", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-maximus-z790-hero", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 2 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 1 },
      { productSlug: "corsair-rm1000x-1000w", componentType: "PSU", quantity: 1 },
      { productSlug: "lian-li-o11-dynamic-evo", componentType: "Case", quantity: 1 },
      { productSlug: "corsair-icue-h150i-elite-lcd", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Titan RTX 4080 Super",
    slug: "scb-titan-rtx-4080-super",
    shortDescription: "High-End Gaming PC for 1440p/4K Gaming",
    description: "Excellent for 1440p 144Hz and 4K 60fps gaming. Perfect balance of performance and value for serious gamers.",
    totalPrice: 260000,
    sellingPrice: 239999,
    compareAtPrice: 269999,
    pcType: "gaming-pc",
    targetUse: "1440p/4K Gaming, Streaming",
    isFeatured: true,
    tags: ["gaming", "high-performance"],
    badges: ["trending", "hot-deal"],
    components: [
      { productSlug: "amd-ryzen-7-7800x3d", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4080-super", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-strix-x670e-e-gaming-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 1 },
      { productSlug: "seasonic-focus-gx-850", componentType: "PSU", quantity: 1 },
      { productSlug: "nzxt-h7-flow", componentType: "Case", quantity: 1 },
      { productSlug: "nzxt-kraken-x73-rgb", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Warrior RTX 4070 Ti Super",
    slug: "scb-warrior-rtx-4070-ti-super",
    shortDescription: "Premium 1440p Gaming Machine",
    description: "Built for 1440p high refresh rate gaming. Crushes all modern games at high settings.",
    totalPrice: 200000,
    sellingPrice: 184999,
    compareAtPrice: 209999,
    pcType: "gaming-pc",
    targetUse: "1440p 144Hz Gaming",
    isFeatured: true,
    tags: ["gaming", "high-performance", "rgb"],
    badges: ["best-seller"],
    components: [
      { productSlug: "intel-core-i7-14700k", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4070-ti-super", componentType: "GPU", quantity: 1 },
      { productSlug: "msi-mag-b760-tomahawk-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "corsair-vengeance-32gb-ddr5-5600", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "evga-supernova-750-g6", componentType: "PSU", quantity: 1 },
      { productSlug: "corsair-4000d-airflow", componentType: "Case", quantity: 1 },
      { productSlug: "deepcool-ak620", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Hunter RTX 4070 Super",
    slug: "scb-hunter-rtx-4070-super",
    shortDescription: "Best Value 1440p Gaming PC",
    description: "Perfect balance of price and performance for 1440p gaming. Great for esports and AAA titles.",
    totalPrice: 150000,
    sellingPrice: 139999,
    compareAtPrice: 159999,
    pcType: "gaming-pc",
    targetUse: "1440p Gaming, Esports",
    tags: ["gaming"],
    badges: ["value-pick", "trending"],
    components: [
      { productSlug: "amd-ryzen-5-7600x", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4070-super", componentType: "GPU", quantity: 1 },
      { productSlug: "gigabyte-b650-aorus-elite-ax", componentType: "Motherboard", quantity: 1 },
      { productSlug: "corsair-vengeance-32gb-ddr5-5600", componentType: "RAM", quantity: 1 },
      { productSlug: "crucial-p3-plus-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "evga-supernova-750-g6", componentType: "PSU", quantity: 1 },
      { productSlug: "corsair-4000d-airflow", componentType: "Case", quantity: 1 },
      { productSlug: "deepcool-ak620", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Striker RTX 4060 Ti",
    slug: "scb-striker-rtx-4060-ti",
    shortDescription: "Solid 1080p/1440p Gaming PC",
    description: "Great for 1080p max settings or 1440p medium-high. Perfect entry into high-performance gaming.",
    totalPrice: 110000,
    sellingPrice: 99999,
    compareAtPrice: 114999,
    pcType: "gaming-pc",
    targetUse: "1080p/1440p Gaming",
    tags: ["gaming"],
    badges: ["hot-deal"],
    components: [
      { productSlug: "amd-ryzen-5-7600x", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4060-ti", componentType: "GPU", quantity: 1 },
      { productSlug: "gigabyte-b650-aorus-elite-ax", componentType: "Motherboard", quantity: 1 },
      { productSlug: "kingston-fury-beast-16gb-ddr5-5200", componentType: "RAM", quantity: 1 },
      { productSlug: "crucial-p3-plus-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "cooler-master-mwe-650w", componentType: "PSU", quantity: 1 },
      { productSlug: "ant-esports-ice-511mt", componentType: "Case", quantity: 1 },
      { productSlug: "cooler-master-hyper-212-rgb", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Rookie RTX 4060",
    slug: "scb-rookie-rtx-4060",
    shortDescription: "Entry Level Gaming PC",
    description: "Perfect starter gaming PC for 1080p gaming. Handles all modern games smoothly.",
    totalPrice: 85000,
    sellingPrice: 74999,
    compareAtPrice: 89999,
    pcType: "gaming-pc",
    targetUse: "1080p Gaming",
    tags: ["gaming", "budget"],
    badges: ["budget-friendly", "best-seller"],
    components: [
      { productSlug: "amd-ryzen-5-5600", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4060", componentType: "GPU", quantity: 1 },
      { productSlug: "asrock-b550m-steel-legend", componentType: "Motherboard", quantity: 1 },
      { productSlug: "corsair-vengeance-lpx-16gb-ddr4-3200", componentType: "RAM", quantity: 1 },
      { productSlug: "crucial-p3-plus-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "cooler-master-mwe-650w", componentType: "PSU", quantity: 1 },
      { productSlug: "ant-esports-ice-511mt", componentType: "Case", quantity: 1 },
      { productSlug: "cooler-master-hyper-212-rgb", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Starter GTX 1650",
    slug: "scb-starter-gtx-1650",
    shortDescription: "Budget Gaming PC",
    description: "Affordable gaming PC for esports and light gaming. Great for students and casual gamers.",
    totalPrice: 55000,
    sellingPrice: 47999,
    compareAtPrice: 54999,
    pcType: "budget-pc",
    targetUse: "Esports, Casual Gaming",
    tags: ["gaming", "budget"],
    badges: ["budget-friendly"],
    components: [
      { productSlug: "amd-ryzen-5-5600", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-gtx-1650", componentType: "GPU", quantity: 1 },
      { productSlug: "asrock-b550m-steel-legend", componentType: "Motherboard", quantity: 1 },
      { productSlug: "kingston-fury-beast-8gb-ddr4-3200", componentType: "RAM", quantity: 2 },
      { productSlug: "crucial-p3-plus-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "cooler-master-mwe-650w", componentType: "PSU", quantity: 1 },
      { productSlug: "ant-esports-ice-511mt", componentType: "Case", quantity: 1 },
    ],
  },
  // ==================== AMD GAMING PCs ====================
  {
    name: "SCB Red Dragon RX 7900 XTX",
    slug: "scb-red-dragon-rx-7900-xtx",
    shortDescription: "Ultimate AMD Gaming PC",
    description: "All-AMD flagship gaming machine. Incredible performance with AMD Ryzen 9 and RX 7900 XTX.",
    totalPrice: 220000,
    sellingPrice: 199999,
    compareAtPrice: 229999,
    pcType: "gaming-pc",
    targetUse: "4K Gaming, Content Creation",
    isFeatured: true,
    tags: ["gaming", "high-performance"],
    badges: ["hot-deal"],
    components: [
      { productSlug: "amd-ryzen-9-7950x", componentType: "CPU", quantity: 1 },
      { productSlug: "amd-rx-7900-xtx", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-strix-x670e-e-gaming-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 1 },
      { productSlug: "corsair-rm1000x-1000w", componentType: "PSU", quantity: 1 },
      { productSlug: "lian-li-o11-dynamic-evo", componentType: "Case", quantity: 1 },
      { productSlug: "nzxt-kraken-x73-rgb", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Red Phoenix RX 7800 XT",
    slug: "scb-red-phoenix-rx-7800-xt",
    shortDescription: "Best Value AMD Gaming PC",
    description: "Excellent 1440p gaming with AMD. Great price-to-performance ratio.",
    totalPrice: 130000,
    sellingPrice: 119999,
    compareAtPrice: 139999,
    pcType: "gaming-pc",
    targetUse: "1440p Gaming",
    tags: ["gaming"],
    badges: ["value-pick"],
    components: [
      { productSlug: "amd-ryzen-7-7800x3d", componentType: "CPU", quantity: 1 },
      { productSlug: "amd-rx-7800-xt", componentType: "GPU", quantity: 1 },
      { productSlug: "gigabyte-b650-aorus-elite-ax", componentType: "Motherboard", quantity: 1 },
      { productSlug: "corsair-vengeance-32gb-ddr5-5600", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "evga-supernova-750-g6", componentType: "PSU", quantity: 1 },
      { productSlug: "corsair-4000d-airflow", componentType: "Case", quantity: 1 },
      { productSlug: "deepcool-ak620", componentType: "Cooler", quantity: 1 },
    ],
  },
  // ==================== STREAMING PCs ====================
  {
    name: "SCB Streamer Pro",
    slug: "scb-streamer-pro",
    shortDescription: "Professional Streaming & Gaming PC",
    description: "Built for streamers. Game and stream simultaneously at high quality with plenty of headroom.",
    totalPrice: 230000,
    sellingPrice: 214999,
    compareAtPrice: 239999,
    pcType: "streaming-pc",
    targetUse: "Streaming, Gaming, Content Creation",
    isFeatured: true,
    tags: ["gaming", "high-performance"],
    badges: ["editors-choice"],
    components: [
      { productSlug: "amd-ryzen-9-7950x", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4080-super", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-strix-x670e-e-gaming-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 2 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 1 },
      { productSlug: "corsair-rm1000x-1000w", componentType: "PSU", quantity: 1 },
      { productSlug: "lian-li-o11-dynamic-evo", componentType: "Case", quantity: 1 },
      { productSlug: "corsair-icue-h150i-elite-lcd", componentType: "Cooler", quantity: 1 },
    ],
  },
  // ==================== WORKSTATION PCs ====================
  {
    name: "SCB Creator Pro",
    slug: "scb-creator-pro",
    shortDescription: "Professional Video Editing Workstation",
    description: "Designed for video editors and content creators. Fast rendering with ample storage and memory.",
    totalPrice: 280000,
    sellingPrice: 259999,
    compareAtPrice: 289999,
    pcType: "video-editing-pc",
    targetUse: "Video Editing, 3D Rendering",
    isFeatured: true,
    tags: ["high-performance", "premium"],
    badges: ["premium"],
    components: [
      { productSlug: "intel-core-i9-14900k", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4080-super", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-maximus-z790-hero", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 2 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 2 },
      { productSlug: "corsair-rm1000x-1000w", componentType: "PSU", quantity: 1 },
      { productSlug: "fractal-design-north", componentType: "Case", quantity: 1 },
      { productSlug: "noctua-nh-d15", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB 3D Master",
    slug: "scb-3d-master",
    shortDescription: "3D Rendering & CAD Workstation",
    description: "Optimized for 3D modeling, rendering, and CAD applications. Maximum compute power.",
    totalPrice: 350000,
    sellingPrice: 319999,
    compareAtPrice: 369999,
    pcType: "3d-rendering-pc",
    targetUse: "3D Rendering, CAD, Animation",
    tags: ["high-performance", "premium"],
    badges: ["premium"],
    components: [
      { productSlug: "amd-ryzen-9-7950x", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4090", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-strix-x670e-e-gaming-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 2 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 2 },
      { productSlug: "corsair-rm1000x-1000w", componentType: "PSU", quantity: 1 },
      { productSlug: "lian-li-o11-dynamic-evo", componentType: "Case", quantity: 1 },
      { productSlug: "corsair-icue-h150i-elite-lcd", componentType: "Cooler", quantity: 1 },
    ],
  },
  // ==================== OFFICE PCs ====================
  {
    name: "SCB Office Pro",
    slug: "scb-office-pro",
    shortDescription: "Professional Office Workstation",
    description: "Reliable office PC for productivity tasks. Fast, quiet, and efficient.",
    totalPrice: 65000,
    sellingPrice: 57999,
    compareAtPrice: 64999,
    pcType: "office-pc",
    targetUse: "Office Work, Productivity",
    tags: ["office", "silent"],
    badges: ["best-seller"],
    components: [
      { productSlug: "intel-core-i5-14600k", componentType: "CPU", quantity: 1 },
      { productSlug: "msi-pro-b660m-a-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "corsair-vengeance-lpx-16gb-ddr4-3200", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "antec-neoeco-550w", componentType: "PSU", quantity: 1 },
      { productSlug: "corsair-4000d-airflow", componentType: "Case", quantity: 1 },
    ],
  },
  {
    name: "SCB Office Essential",
    slug: "scb-office-essential",
    shortDescription: "Budget Office PC",
    description: "Affordable and reliable for everyday office tasks. Perfect for businesses.",
    totalPrice: 40000,
    sellingPrice: 34999,
    compareAtPrice: 39999,
    pcType: "office-pc",
    targetUse: "Office Work, Web Browsing",
    tags: ["office", "budget"],
    badges: ["budget-friendly"],
    components: [
      { productSlug: "intel-core-i3-14100", componentType: "CPU", quantity: 1 },
      { productSlug: "msi-pro-b660m-a-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "kingston-fury-beast-8gb-ddr4-3200", componentType: "RAM", quantity: 1 },
      { productSlug: "crucial-p3-plus-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "antec-neoeco-550w", componentType: "PSU", quantity: 1 },
      { productSlug: "ant-esports-ice-511mt", componentType: "Case", quantity: 1 },
    ],
  },
  // ==================== MINI PCs ====================
  {
    name: "SCB Mini Beast",
    slug: "scb-mini-beast",
    shortDescription: "Compact Powerhouse Mini PC",
    description: "Maximum performance in minimum space. Perfect for small desks and living room gaming.",
    totalPrice: 180000,
    sellingPrice: 164999,
    compareAtPrice: 189999,
    pcType: "mini-pc",
    targetUse: "Gaming, Living Room PC",
    tags: ["gaming", "compact", "mini-itx"],
    badges: ["trending"],
    components: [
      { productSlug: "amd-ryzen-7-7800x3d", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4070-super", componentType: "GPU", quantity: 1 },
      { productSlug: "gigabyte-b650-aorus-elite-ax", componentType: "Motherboard", quantity: 1 },
      { productSlug: "corsair-vengeance-32gb-ddr5-5600", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "cooler-master-nr200p-max", componentType: "Case+PSU+AIO", quantity: 1 },
    ],
  },
  {
    name: "SCB Mini Office",
    slug: "scb-mini-office",
    shortDescription: "Compact Office Mini PC",
    description: "Space-saving office PC. Small footprint, big productivity.",
    totalPrice: 50000,
    sellingPrice: 44999,
    compareAtPrice: 52999,
    pcType: "mini-pc",
    targetUse: "Office, Home Theater",
    tags: ["office", "compact", "silent"],
    badges: ["value-pick"],
    components: [
      { productSlug: "intel-core-i5-14600k", componentType: "CPU", quantity: 1 },
      { productSlug: "msi-pro-b660m-a-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "kingston-fury-beast-16gb-ddr5-5200", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "antec-neoeco-550w", componentType: "PSU", quantity: 1 },
      { productSlug: "ant-esports-ice-511mt", componentType: "Case", quantity: 1 },
    ],
  },
  // ==================== SPECIAL BUILDS ====================
  {
    name: "SCB RGB Showcase",
    slug: "scb-rgb-showcase",
    shortDescription: "Ultimate RGB Gaming Build",
    description: "For those who want their PC to be a centerpiece. Full RGB everything with glass panels.",
    totalPrice: 200000,
    sellingPrice: 184999,
    compareAtPrice: 209999,
    pcType: "gaming-pc",
    targetUse: "Gaming, Showcase",
    tags: ["gaming", "rgb", "premium"],
    badges: ["trending"],
    components: [
      { productSlug: "intel-core-i7-14700k", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4070-ti-super", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-maximus-z790-hero", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 1 },
      { productSlug: "corsair-rm1000x-1000w", componentType: "PSU", quantity: 1 },
      { productSlug: "lian-li-o11-dynamic-evo", componentType: "Case", quantity: 1 },
      { productSlug: "corsair-icue-h150i-elite-lcd", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Silent Performer",
    slug: "scb-silent-performer",
    shortDescription: "Whisper-Quiet High Performance PC",
    description: "Maximum performance with minimum noise. Perfect for recording studios and quiet environments.",
    totalPrice: 190000,
    sellingPrice: 174999,
    compareAtPrice: 199999,
    pcType: "workstation",
    targetUse: "Recording, Quiet Office",
    tags: ["high-performance", "silent"],
    badges: ["editors-choice"],
    components: [
      { productSlug: "intel-core-i7-14700k", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4070-super", componentType: "GPU", quantity: 1 },
      { productSlug: "msi-mag-b760-tomahawk-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "corsair-vengeance-32gb-ddr5-5600", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 1 },
      { productSlug: "seasonic-focus-gx-850", componentType: "PSU", quantity: 1 },
      { productSlug: "fractal-design-north", componentType: "Case", quantity: 1 },
      { productSlug: "noctua-nh-d15", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Student Special",
    slug: "scb-student-special",
    shortDescription: "Affordable PC for Students",
    description: "Perfect for students. Handles schoolwork, light gaming, and everyday tasks.",
    totalPrice: 35000,
    sellingPrice: 29999,
    compareAtPrice: 34999,
    pcType: "budget-pc",
    targetUse: "Study, Light Gaming, General Use",
    tags: ["budget", "office"],
    badges: ["budget-friendly", "best-seller"],
    components: [
      { productSlug: "intel-core-i3-14100", componentType: "CPU", quantity: 1 },
      { productSlug: "msi-pro-b660m-a-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "kingston-fury-beast-8gb-ddr4-3200", componentType: "RAM", quantity: 1 },
      { productSlug: "crucial-p3-plus-1tb", componentType: "Storage", quantity: 1 },
      { productSlug: "antec-neoeco-550w", componentType: "PSU", quantity: 1 },
      { productSlug: "ant-esports-ice-511mt", componentType: "Case", quantity: 1 },
    ],
  },
  // ==================== COMING SOON PCs ====================
  {
    name: "SCB Phantom RTX 5090",
    slug: "scb-phantom-rtx-5090",
    shortDescription: "Next-Gen Ultimate Gaming Beast - RTX 5090",
    description: "The future of gaming is here. Featuring the upcoming NVIDIA RTX 5090 with next-gen architecture. Be ready for 8K gaming and unprecedented ray tracing performance.",
    totalPrice: 450000,
    sellingPrice: 424999,
    compareAtPrice: 479999,
    pcType: "gaming-pc",
    targetUse: "8K Gaming, Next-Gen Gaming, Content Creation",
    isFeatured: true,
    isComingSoon: true,
    launchDate: new Date("2025-03-15"),
    tags: ["gaming", "premium", "next-gen"],
    badges: ["premium", "coming-soon"],
    components: [
      { productSlug: "intel-core-i9-14900k", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4090", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-maximus-z790-hero", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 2 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 2 },
      { productSlug: "corsair-rm1000x-1000w", componentType: "PSU", quantity: 1 },
      { productSlug: "lian-li-o11-dynamic-evo", componentType: "Case", quantity: 1 },
      { productSlug: "corsair-icue-h150i-elite-lcd", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB AI Workstation Pro",
    slug: "scb-ai-workstation-pro",
    shortDescription: "Professional AI & Machine Learning Workstation",
    description: "Purpose-built for AI researchers and data scientists. Dual GPU configuration for training large models. Optimized for TensorFlow, PyTorch, and CUDA workflows.",
    totalPrice: 550000,
    sellingPrice: 499999,
    compareAtPrice: 589999,
    pcType: "workstation",
    targetUse: "AI/ML Training, Deep Learning, Data Science",
    isFeatured: true,
    isComingSoon: true,
    launchDate: new Date("2025-02-28"),
    tags: ["workstation", "ai", "premium"],
    badges: ["premium", "coming-soon"],
    components: [
      { productSlug: "amd-ryzen-9-7950x", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4090", componentType: "GPU", quantity: 1 },
      { productSlug: "asus-rog-strix-x670e-e-gaming-wifi", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 4 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 2 },
      { productSlug: "corsair-rm1000x-1000w", componentType: "PSU", quantity: 1 },
      { productSlug: "fractal-design-north", componentType: "Case", quantity: 1 },
      { productSlug: "noctua-nh-d15", componentType: "Cooler", quantity: 1 },
    ],
  },
  {
    name: "SCB Compact Gaming Cube",
    slug: "scb-compact-gaming-cube",
    shortDescription: "Ultra Compact Mini-ITX Gaming Powerhouse",
    description: "Maximum gaming power in minimum space. Custom loop water cooling in a shoebox-sized case. Perfect for LAN parties and small spaces without compromising performance.",
    totalPrice: 280000,
    sellingPrice: 259999,
    compareAtPrice: 299999,
    pcType: "mini-pc",
    targetUse: "Compact Gaming, LAN Parties, Living Room",
    isFeatured: true,
    isComingSoon: true,
    launchDate: new Date("2025-02-15"),
    tags: ["gaming", "compact", "mini-itx", "premium"],
    badges: ["trending", "coming-soon"],
    components: [
      { productSlug: "amd-ryzen-7-7800x3d", componentType: "CPU", quantity: 1 },
      { productSlug: "nvidia-rtx-4080-super", componentType: "GPU", quantity: 1 },
      { productSlug: "gigabyte-b650-aorus-elite-ax", componentType: "Motherboard", quantity: 1 },
      { productSlug: "gskill-trident-z5-rgb-32gb-ddr5-6000", componentType: "RAM", quantity: 1 },
      { productSlug: "samsung-990-pro-2tb", componentType: "Storage", quantity: 1 },
      { productSlug: "cooler-master-nr200p-max", componentType: "Case+PSU+AIO", quantity: 1 },
    ],
  },
];
