// Products data for seeding - 100+ products across all categories

export interface ProductData {
  name: string;
  slug: string;
  shortDescription: string;
  price: number;
  compareAtPrice?: number;
  brand: string;
  model?: string;
  category: string;
  specs: Array<{ key: string; value: string }>;
  tags?: string[];
  badges?: string[];
  isFeatured?: boolean;
}

// ==================== PROCESSORS ====================
export const processors: ProductData[] = [
  {
    name: "AMD Ryzen 9 7950X",
    slug: "amd-ryzen-9-7950x",
    shortDescription: "16-Core, 32-Thread Desktop Processor",
    price: 54999,
    compareAtPrice: 62999,
    brand: "AMD",
    model: "7950X",
    category: "processors",
    isFeatured: true,
    tags: ["high-performance", "overclocking"],
    badges: ["best-seller"],
    specs: [
      { key: "Cores", value: "16" },
      { key: "Threads", value: "32" },
      { key: "Base Clock", value: "4.5 GHz" },
      { key: "Boost Clock", value: "5.7 GHz" },
      { key: "TDP", value: "170W" },
      { key: "Socket", value: "AM5" },
    ],
  },
  {
    name: "AMD Ryzen 7 7800X3D",
    slug: "amd-ryzen-7-7800x3d",
    shortDescription: "8-Core Gaming Processor with 3D V-Cache",
    price: 44999,
    compareAtPrice: 49999,
    brand: "AMD",
    model: "7800X3D",
    category: "processors",
    isFeatured: true,
    tags: ["gaming", "high-performance"],
    badges: ["hot-deal", "trending"],
    specs: [
      { key: "Cores", value: "8" },
      { key: "Threads", value: "16" },
      { key: "Base Clock", value: "4.2 GHz" },
      { key: "Boost Clock", value: "5.0 GHz" },
      { key: "L3 Cache", value: "96MB" },
      { key: "Socket", value: "AM5" },
    ],
  },
  {
    name: "AMD Ryzen 5 7600X",
    slug: "amd-ryzen-5-7600x",
    shortDescription: "6-Core Desktop Processor",
    price: 22999,
    compareAtPrice: 26999,
    brand: "AMD",
    model: "7600X",
    category: "processors",
    tags: ["gaming", "budget"],
    badges: ["value-pick"],
    specs: [
      { key: "Cores", value: "6" },
      { key: "Threads", value: "12" },
      { key: "Base Clock", value: "4.7 GHz" },
      { key: "Boost Clock", value: "5.3 GHz" },
      { key: "TDP", value: "105W" },
      { key: "Socket", value: "AM5" },
    ],
  },
  {
    name: "Intel Core i9-14900K",
    slug: "intel-core-i9-14900k",
    shortDescription: "24-Core Desktop Processor",
    price: 59999,
    compareAtPrice: 65999,
    brand: "Intel",
    model: "i9-14900K",
    category: "processors",
    isFeatured: true,
    tags: ["high-performance", "overclocking"],
    badges: ["premium", "new-arrival"],
    specs: [
      { key: "P-Cores", value: "8" },
      { key: "E-Cores", value: "16" },
      { key: "Threads", value: "32" },
      { key: "Base Clock", value: "3.2 GHz" },
      { key: "Boost Clock", value: "6.0 GHz" },
      { key: "Socket", value: "LGA 1700" },
    ],
  },
  {
    name: "Intel Core i7-14700K",
    slug: "intel-core-i7-14700k",
    shortDescription: "20-Core Desktop Processor",
    price: 44999,
    compareAtPrice: 49999,
    brand: "Intel",
    model: "i7-14700K",
    category: "processors",
    tags: ["gaming", "high-performance"],
    badges: ["trending"],
    specs: [
      { key: "P-Cores", value: "8" },
      { key: "E-Cores", value: "12" },
      { key: "Threads", value: "28" },
      { key: "Boost Clock", value: "5.6 GHz" },
      { key: "Socket", value: "LGA 1700" },
    ],
  },
  {
    name: "Intel Core i5-14600K",
    slug: "intel-core-i5-14600k",
    shortDescription: "14-Core Desktop Processor",
    price: 29999,
    compareAtPrice: 33999,
    brand: "Intel",
    model: "i5-14600K",
    category: "processors",
    tags: ["gaming"],
    badges: ["value-pick"],
    specs: [
      { key: "P-Cores", value: "6" },
      { key: "E-Cores", value: "8" },
      { key: "Threads", value: "20" },
      { key: "Boost Clock", value: "5.3 GHz" },
      { key: "Socket", value: "LGA 1700" },
    ],
  },
  {
    name: "AMD Ryzen 5 5600",
    slug: "amd-ryzen-5-5600",
    shortDescription: "6-Core Budget Gaming Processor",
    price: 12999,
    compareAtPrice: 15999,
    brand: "AMD",
    model: "5600",
    category: "processors",
    tags: ["budget", "gaming"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Cores", value: "6" },
      { key: "Threads", value: "12" },
      { key: "Base Clock", value: "3.5 GHz" },
      { key: "Boost Clock", value: "4.4 GHz" },
      { key: "Socket", value: "AM4" },
    ],
  },
  {
    name: "Intel Core i3-14100",
    slug: "intel-core-i3-14100",
    shortDescription: "4-Core Entry Level Processor",
    price: 11999,
    brand: "Intel",
    model: "i3-14100",
    category: "processors",
    tags: ["budget", "office"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Cores", value: "4" },
      { key: "Threads", value: "8" },
      { key: "Boost Clock", value: "4.7 GHz" },
      { key: "Socket", value: "LGA 1700" },
    ],
  },
];

// ==================== GRAPHICS CARDS ====================
export const graphicsCards: ProductData[] = [
  {
    name: "NVIDIA GeForce RTX 4090",
    slug: "nvidia-rtx-4090",
    shortDescription: "24GB GDDR6X Ultimate Gaming GPU",
    price: 174999,
    compareAtPrice: 189999,
    brand: "NVIDIA",
    model: "RTX 4090",
    category: "graphics-cards",
    isFeatured: true,
    tags: ["gaming", "high-performance"],
    badges: ["premium"],
    specs: [
      { key: "Memory", value: "24GB GDDR6X" },
      { key: "CUDA Cores", value: "16384" },
      { key: "Boost Clock", value: "2.52 GHz" },
      { key: "TDP", value: "450W" },
      { key: "Interface", value: "PCIe 4.0" },
    ],
  },
  {
    name: "NVIDIA GeForce RTX 4080 Super",
    slug: "nvidia-rtx-4080-super",
    shortDescription: "16GB GDDR6X High-End Gaming GPU",
    price: 109999,
    compareAtPrice: 119999,
    brand: "NVIDIA",
    model: "RTX 4080 Super",
    category: "graphics-cards",
    isFeatured: true,
    tags: ["gaming", "high-performance"],
    badges: ["new-arrival"],
    specs: [
      { key: "Memory", value: "16GB GDDR6X" },
      { key: "CUDA Cores", value: "10240" },
      { key: "Boost Clock", value: "2.55 GHz" },
      { key: "TDP", value: "320W" },
    ],
  },
  {
    name: "NVIDIA GeForce RTX 4070 Ti Super",
    slug: "nvidia-rtx-4070-ti-super",
    shortDescription: "16GB GDDR6X Gaming GPU",
    price: 84999,
    compareAtPrice: 89999,
    brand: "NVIDIA",
    model: "RTX 4070 Ti Super",
    category: "graphics-cards",
    tags: ["gaming", "high-performance"],
    badges: ["trending"],
    specs: [
      { key: "Memory", value: "16GB GDDR6X" },
      { key: "CUDA Cores", value: "8448" },
      { key: "Boost Clock", value: "2.61 GHz" },
      { key: "TDP", value: "285W" },
    ],
  },
  {
    name: "NVIDIA GeForce RTX 4070 Super",
    slug: "nvidia-rtx-4070-super",
    shortDescription: "12GB GDDR6X Gaming GPU",
    price: 59999,
    compareAtPrice: 64999,
    brand: "NVIDIA",
    model: "RTX 4070 Super",
    category: "graphics-cards",
    tags: ["gaming"],
    badges: ["value-pick", "best-seller"],
    specs: [
      { key: "Memory", value: "12GB GDDR6X" },
      { key: "CUDA Cores", value: "7168" },
      { key: "Boost Clock", value: "2.48 GHz" },
      { key: "TDP", value: "220W" },
    ],
  },
  {
    name: "NVIDIA GeForce RTX 4060 Ti",
    slug: "nvidia-rtx-4060-ti",
    shortDescription: "8GB GDDR6 Gaming GPU",
    price: 42999,
    compareAtPrice: 46999,
    brand: "NVIDIA",
    model: "RTX 4060 Ti",
    category: "graphics-cards",
    tags: ["gaming"],
    specs: [
      { key: "Memory", value: "8GB GDDR6" },
      { key: "CUDA Cores", value: "4352" },
      { key: "Boost Clock", value: "2.54 GHz" },
      { key: "TDP", value: "160W" },
    ],
  },
  {
    name: "NVIDIA GeForce RTX 4060",
    slug: "nvidia-rtx-4060",
    shortDescription: "8GB GDDR6 Entry Gaming GPU",
    price: 29999,
    compareAtPrice: 33999,
    brand: "NVIDIA",
    model: "RTX 4060",
    category: "graphics-cards",
    tags: ["gaming", "budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Memory", value: "8GB GDDR6" },
      { key: "CUDA Cores", value: "3072" },
      { key: "TDP", value: "115W" },
    ],
  },
  {
    name: "AMD Radeon RX 7900 XTX",
    slug: "amd-rx-7900-xtx",
    shortDescription: "24GB GDDR6 Flagship GPU",
    price: 94999,
    compareAtPrice: 104999,
    brand: "AMD",
    model: "RX 7900 XTX",
    category: "graphics-cards",
    tags: ["gaming", "high-performance"],
    badges: ["hot-deal"],
    specs: [
      { key: "Memory", value: "24GB GDDR6" },
      { key: "Stream Processors", value: "6144" },
      { key: "Boost Clock", value: "2.5 GHz" },
      { key: "TDP", value: "355W" },
    ],
  },
  {
    name: "AMD Radeon RX 7800 XT",
    slug: "amd-rx-7800-xt",
    shortDescription: "16GB GDDR6 Gaming GPU",
    price: 49999,
    compareAtPrice: 54999,
    brand: "AMD",
    model: "RX 7800 XT",
    category: "graphics-cards",
    tags: ["gaming"],
    badges: ["value-pick"],
    specs: [
      { key: "Memory", value: "16GB GDDR6" },
      { key: "Stream Processors", value: "3840" },
      { key: "TDP", value: "263W" },
    ],
  },
  {
    name: "NVIDIA GeForce GTX 1650",
    slug: "nvidia-gtx-1650",
    shortDescription: "4GB GDDR6 Budget GPU",
    price: 14999,
    brand: "NVIDIA",
    model: "GTX 1650",
    category: "graphics-cards",
    tags: ["budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Memory", value: "4GB GDDR6" },
      { key: "CUDA Cores", value: "896" },
      { key: "TDP", value: "75W" },
    ],
  },
];

// ==================== MOTHERBOARDS ====================
export const motherboards: ProductData[] = [
  {
    name: "ASUS ROG Maximus Z790 Hero",
    slug: "asus-rog-maximus-z790-hero",
    shortDescription: "Intel Z790 ATX Gaming Motherboard",
    price: 64999,
    compareAtPrice: 72999,
    brand: "ASUS",
    model: "ROG Maximus Z790 Hero",
    category: "motherboards",
    isFeatured: true,
    tags: ["gaming", "premium", "atx"],
    badges: ["premium"],
    specs: [
      { key: "Chipset", value: "Intel Z790" },
      { key: "Socket", value: "LGA 1700" },
      { key: "Form Factor", value: "ATX" },
      { key: "RAM Slots", value: "4x DDR5" },
      { key: "Max RAM", value: "192GB" },
    ],
  },
  {
    name: "MSI MAG B760 Tomahawk WiFi",
    slug: "msi-mag-b760-tomahawk-wifi",
    shortDescription: "Intel B760 ATX Motherboard with WiFi",
    price: 21999,
    compareAtPrice: 24999,
    brand: "MSI",
    model: "MAG B760 Tomahawk WiFi",
    category: "motherboards",
    tags: ["gaming", "atx"],
    badges: ["best-seller"],
    specs: [
      { key: "Chipset", value: "Intel B760" },
      { key: "Socket", value: "LGA 1700" },
      { key: "Form Factor", value: "ATX" },
      { key: "RAM Slots", value: "4x DDR5" },
      { key: "WiFi", value: "WiFi 6E" },
    ],
  },
  {
    name: "Gigabyte B650 Aorus Elite AX",
    slug: "gigabyte-b650-aorus-elite-ax",
    shortDescription: "AMD B650 ATX Motherboard",
    price: 22999,
    compareAtPrice: 26999,
    brand: "Gigabyte",
    model: "B650 Aorus Elite AX",
    category: "motherboards",
    tags: ["gaming", "atx"],
    badges: ["value-pick"],
    specs: [
      { key: "Chipset", value: "AMD B650" },
      { key: "Socket", value: "AM5" },
      { key: "Form Factor", value: "ATX" },
      { key: "RAM Slots", value: "4x DDR5" },
      { key: "WiFi", value: "WiFi 6E" },
    ],
  },
  {
    name: "ASUS ROG Strix X670E-E Gaming WiFi",
    slug: "asus-rog-strix-x670e-e-gaming-wifi",
    shortDescription: "AMD X670E Premium Gaming Motherboard",
    price: 49999,
    compareAtPrice: 54999,
    brand: "ASUS",
    model: "ROG Strix X670E-E",
    category: "motherboards",
    isFeatured: true,
    tags: ["gaming", "premium", "atx"],
    badges: ["premium"],
    specs: [
      { key: "Chipset", value: "AMD X670E" },
      { key: "Socket", value: "AM5" },
      { key: "Form Factor", value: "ATX" },
      { key: "RAM Slots", value: "4x DDR5" },
    ],
  },
  {
    name: "MSI PRO B660M-A WiFi",
    slug: "msi-pro-b660m-a-wifi",
    shortDescription: "Intel B660 Micro ATX Motherboard",
    price: 12999,
    brand: "MSI",
    model: "PRO B660M-A WiFi",
    category: "motherboards",
    tags: ["office", "compact"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Chipset", value: "Intel B660" },
      { key: "Socket", value: "LGA 1700" },
      { key: "Form Factor", value: "Micro ATX" },
      { key: "RAM Slots", value: "2x DDR4" },
    ],
  },
  {
    name: "ASRock B550M Steel Legend",
    slug: "asrock-b550m-steel-legend",
    shortDescription: "AMD B550 Micro ATX Motherboard",
    price: 11999,
    compareAtPrice: 13999,
    brand: "ASRock",
    model: "B550M Steel Legend",
    category: "motherboards",
    tags: ["gaming", "compact", "ddr4"],
    specs: [
      { key: "Chipset", value: "AMD B550" },
      { key: "Socket", value: "AM4" },
      { key: "Form Factor", value: "Micro ATX" },
      { key: "RAM Slots", value: "4x DDR4" },
    ],
  },
];

// ==================== RAM ====================
export const ram: ProductData[] = [
  {
    name: "G.Skill Trident Z5 RGB 32GB DDR5-6000",
    slug: "gskill-trident-z5-rgb-32gb-ddr5-6000",
    shortDescription: "32GB (2x16GB) DDR5 6000MHz RGB RAM",
    price: 14999,
    compareAtPrice: 17999,
    brand: "G.Skill",
    model: "Trident Z5 RGB",
    category: "ram",
    isFeatured: true,
    tags: ["ddr5", "rgb", "gaming"],
    badges: ["best-seller"],
    specs: [
      { key: "Capacity", value: "32GB (2x16GB)" },
      { key: "Speed", value: "6000MHz" },
      { key: "Type", value: "DDR5" },
      { key: "CL", value: "CL30" },
      { key: "RGB", value: "Yes" },
    ],
  },
  {
    name: "Corsair Vengeance 32GB DDR5-5600",
    slug: "corsair-vengeance-32gb-ddr5-5600",
    shortDescription: "32GB (2x16GB) DDR5 5600MHz RAM",
    price: 11999,
    compareAtPrice: 14999,
    brand: "Corsair",
    model: "Vengeance DDR5",
    category: "ram",
    tags: ["ddr5", "gaming"],
    badges: ["value-pick"],
    specs: [
      { key: "Capacity", value: "32GB (2x16GB)" },
      { key: "Speed", value: "5600MHz" },
      { key: "Type", value: "DDR5" },
      { key: "CL", value: "CL36" },
    ],
  },
  {
    name: "Kingston Fury Beast 16GB DDR5-5200",
    slug: "kingston-fury-beast-16gb-ddr5-5200",
    shortDescription: "16GB (2x8GB) DDR5 5200MHz RAM",
    price: 6999,
    brand: "Kingston",
    model: "Fury Beast DDR5",
    category: "ram",
    tags: ["ddr5"],
    specs: [
      { key: "Capacity", value: "16GB (2x8GB)" },
      { key: "Speed", value: "5200MHz" },
      { key: "Type", value: "DDR5" },
    ],
  },
  {
    name: "G.Skill Ripjaws V 32GB DDR4-3200",
    slug: "gskill-ripjaws-v-32gb-ddr4-3200",
    shortDescription: "32GB (2x16GB) DDR4 3200MHz RAM",
    price: 6499,
    compareAtPrice: 7999,
    brand: "G.Skill",
    model: "Ripjaws V",
    category: "ram",
    tags: ["ddr4", "gaming"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Capacity", value: "32GB (2x16GB)" },
      { key: "Speed", value: "3200MHz" },
      { key: "Type", value: "DDR4" },
      { key: "CL", value: "CL16" },
    ],
  },
  {
    name: "Corsair Vengeance LPX 16GB DDR4-3200",
    slug: "corsair-vengeance-lpx-16gb-ddr4-3200",
    shortDescription: "16GB (2x8GB) DDR4 3200MHz RAM",
    price: 3499,
    brand: "Corsair",
    model: "Vengeance LPX",
    category: "ram",
    tags: ["ddr4", "budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Capacity", value: "16GB (2x8GB)" },
      { key: "Speed", value: "3200MHz" },
      { key: "Type", value: "DDR4" },
    ],
  },
  {
    name: "Kingston Fury Beast 8GB DDR4-3200",
    slug: "kingston-fury-beast-8gb-ddr4-3200",
    shortDescription: "8GB DDR4 3200MHz RAM",
    price: 1899,
    brand: "Kingston",
    model: "Fury Beast DDR4",
    category: "ram",
    tags: ["ddr4", "budget"],
    specs: [
      { key: "Capacity", value: "8GB" },
      { key: "Speed", value: "3200MHz" },
      { key: "Type", value: "DDR4" },
    ],
  },
];

// ==================== STORAGE ====================
export const storage: ProductData[] = [
  {
    name: "Samsung 990 Pro 2TB NVMe SSD",
    slug: "samsung-990-pro-2tb",
    shortDescription: "2TB PCIe 4.0 NVMe M.2 SSD",
    price: 16999,
    compareAtPrice: 19999,
    brand: "Samsung",
    model: "990 Pro",
    category: "nvme-ssd",
    isFeatured: true,
    tags: ["nvme", "high-performance"],
    badges: ["best-seller"],
    specs: [
      { key: "Capacity", value: "2TB" },
      { key: "Read Speed", value: "7450 MB/s" },
      { key: "Write Speed", value: "6900 MB/s" },
      { key: "Interface", value: "PCIe 4.0 x4" },
      { key: "Form Factor", value: "M.2 2280" },
    ],
  },
  {
    name: "Samsung 990 Pro 1TB NVMe SSD",
    slug: "samsung-990-pro-1tb",
    shortDescription: "1TB PCIe 4.0 NVMe M.2 SSD",
    price: 9999,
    compareAtPrice: 11999,
    brand: "Samsung",
    model: "990 Pro",
    category: "nvme-ssd",
    tags: ["nvme", "high-performance"],
    badges: ["trending"],
    specs: [
      { key: "Capacity", value: "1TB" },
      { key: "Read Speed", value: "7450 MB/s" },
      { key: "Write Speed", value: "6900 MB/s" },
      { key: "Interface", value: "PCIe 4.0 x4" },
    ],
  },
  {
    name: "WD Black SN850X 1TB NVMe SSD",
    slug: "wd-black-sn850x-1tb",
    shortDescription: "1TB PCIe 4.0 NVMe Gaming SSD",
    price: 8999,
    brand: "Western Digital",
    model: "SN850X",
    category: "nvme-ssd",
    tags: ["nvme", "gaming"],
    specs: [
      { key: "Capacity", value: "1TB" },
      { key: "Read Speed", value: "7300 MB/s" },
      { key: "Write Speed", value: "6300 MB/s" },
    ],
  },
  {
    name: "Crucial P3 Plus 1TB NVMe SSD",
    slug: "crucial-p3-plus-1tb",
    shortDescription: "1TB PCIe 4.0 NVMe M.2 SSD",
    price: 5499,
    brand: "Crucial",
    model: "P3 Plus",
    category: "nvme-ssd",
    tags: ["nvme", "budget"],
    badges: ["value-pick"],
    specs: [
      { key: "Capacity", value: "1TB" },
      { key: "Read Speed", value: "5000 MB/s" },
      { key: "Write Speed", value: "4200 MB/s" },
    ],
  },
  {
    name: "Samsung 870 EVO 1TB SATA SSD",
    slug: "samsung-870-evo-1tb",
    shortDescription: "1TB 2.5-inch SATA SSD",
    price: 6499,
    brand: "Samsung",
    model: "870 EVO",
    category: "internal-ssd",
    tags: ["budget"],
    specs: [
      { key: "Capacity", value: "1TB" },
      { key: "Read Speed", value: "560 MB/s" },
      { key: "Write Speed", value: "530 MB/s" },
      { key: "Interface", value: "SATA III" },
    ],
  },
  {
    name: "Seagate Barracuda 2TB HDD",
    slug: "seagate-barracuda-2tb",
    shortDescription: "2TB 7200RPM Internal Hard Drive",
    price: 4999,
    brand: "Seagate",
    model: "Barracuda",
    category: "internal-hdd",
    tags: ["budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Capacity", value: "2TB" },
      { key: "Speed", value: "7200 RPM" },
      { key: "Cache", value: "256MB" },
      { key: "Interface", value: "SATA III" },
    ],
  },
  {
    name: "WD Blue 4TB HDD",
    slug: "wd-blue-4tb",
    shortDescription: "4TB 5400RPM Internal Hard Drive",
    price: 7999,
    brand: "Western Digital",
    model: "WD Blue",
    category: "internal-hdd",
    specs: [
      { key: "Capacity", value: "4TB" },
      { key: "Speed", value: "5400 RPM" },
      { key: "Cache", value: "256MB" },
    ],
  },
  {
    name: "WD Elements 1TB External HDD",
    slug: "wd-elements-1tb-external",
    shortDescription: "1TB USB 3.0 Portable External HDD",
    price: 3999,
    brand: "Western Digital",
    model: "Elements",
    category: "external-hdd",
    badges: ["budget-friendly"],
    specs: [
      { key: "Capacity", value: "1TB" },
      { key: "Interface", value: "USB 3.0" },
      { key: "Form Factor", value: "2.5-inch Portable" },
    ],
  },
  {
    name: "SanDisk Ultra 128GB USB Drive",
    slug: "sandisk-ultra-128gb-usb",
    shortDescription: "128GB USB 3.0 Flash Drive",
    price: 899,
    brand: "SanDisk",
    model: "Ultra",
    category: "pen-drives",
    specs: [
      { key: "Capacity", value: "128GB" },
      { key: "Interface", value: "USB 3.0" },
      { key: "Read Speed", value: "130 MB/s" },
    ],
  },
  {
    name: "SanDisk Extreme 256GB microSD",
    slug: "sandisk-extreme-256gb-microsd",
    shortDescription: "256GB microSDXC UHS-I Card",
    price: 2499,
    brand: "SanDisk",
    model: "Extreme",
    category: "memory-cards",
    specs: [
      { key: "Capacity", value: "256GB" },
      { key: "Read Speed", value: "190 MB/s" },
      { key: "Write Speed", value: "130 MB/s" },
    ],
  },
];

// ==================== POWER SUPPLIES ====================
export const powerSupplies: ProductData[] = [
  {
    name: "Corsair RM1000x 1000W 80+ Gold",
    slug: "corsair-rm1000x-1000w",
    shortDescription: "1000W Fully Modular ATX PSU",
    price: 14999,
    compareAtPrice: 16999,
    brand: "Corsair",
    model: "RM1000x",
    category: "power-supplies",
    isFeatured: true,
    tags: ["modular", "high-performance"],
    badges: ["best-seller"],
    specs: [
      { key: "Wattage", value: "1000W" },
      { key: "Efficiency", value: "80+ Gold" },
      { key: "Modular", value: "Fully Modular" },
      { key: "Fan Size", value: "135mm" },
    ],
  },
  {
    name: "Seasonic Focus GX-850 850W",
    slug: "seasonic-focus-gx-850",
    shortDescription: "850W Fully Modular 80+ Gold PSU",
    price: 11999,
    brand: "Seasonic",
    model: "Focus GX-850",
    category: "power-supplies",
    tags: ["modular"],
    badges: ["value-pick"],
    specs: [
      { key: "Wattage", value: "850W" },
      { key: "Efficiency", value: "80+ Gold" },
      { key: "Modular", value: "Fully Modular" },
    ],
  },
  {
    name: "EVGA SuperNOVA 750 G6",
    slug: "evga-supernova-750-g6",
    shortDescription: "750W Fully Modular 80+ Gold PSU",
    price: 9499,
    brand: "EVGA",
    model: "SuperNOVA 750 G6",
    category: "power-supplies",
    tags: ["modular"],
    specs: [
      { key: "Wattage", value: "750W" },
      { key: "Efficiency", value: "80+ Gold" },
      { key: "Modular", value: "Fully Modular" },
    ],
  },
  {
    name: "Cooler Master MWE 650W Bronze V2",
    slug: "cooler-master-mwe-650w",
    shortDescription: "650W 80+ Bronze Non-Modular PSU",
    price: 4999,
    brand: "Cooler Master",
    model: "MWE 650 Bronze V2",
    category: "power-supplies",
    tags: ["budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Wattage", value: "650W" },
      { key: "Efficiency", value: "80+ Bronze" },
      { key: "Modular", value: "Non-Modular" },
    ],
  },
  {
    name: "Antec NeoECO 550W Gold",
    slug: "antec-neoeco-550w",
    shortDescription: "550W Semi-Modular 80+ Gold PSU",
    price: 5499,
    brand: "Antec",
    model: "NeoECO Gold",
    category: "power-supplies",
    tags: ["budget"],
    specs: [
      { key: "Wattage", value: "550W" },
      { key: "Efficiency", value: "80+ Gold" },
      { key: "Modular", value: "Semi-Modular" },
    ],
  },
];

// ==================== PC CASES ====================
export const pcCases: ProductData[] = [
  {
    name: "Lian Li O11 Dynamic EVO",
    slug: "lian-li-o11-dynamic-evo",
    shortDescription: "Mid-Tower ATX Case with Dual Chamber",
    price: 16999,
    compareAtPrice: 18999,
    brand: "Lian Li",
    model: "O11 Dynamic EVO",
    category: "pc-cases",
    isFeatured: true,
    tags: ["gaming", "atx", "rgb"],
    badges: ["best-seller"],
    specs: [
      { key: "Form Factor", value: "Mid-Tower" },
      { key: "Motherboard Support", value: "E-ATX, ATX, Micro-ATX, Mini-ITX" },
      { key: "GPU Clearance", value: "420mm" },
      { key: "Drive Bays", value: "3x 2.5\" + 2x 3.5\"" },
    ],
  },
  {
    name: "NZXT H7 Flow",
    slug: "nzxt-h7-flow",
    shortDescription: "Mid-Tower ATX Airflow Case",
    price: 12999,
    brand: "NZXT",
    model: "H7 Flow",
    category: "pc-cases",
    tags: ["gaming", "atx"],
    badges: ["trending"],
    specs: [
      { key: "Form Factor", value: "Mid-Tower" },
      { key: "Motherboard Support", value: "ATX, Micro-ATX, Mini-ITX" },
      { key: "GPU Clearance", value: "400mm" },
    ],
  },
  {
    name: "Corsair 4000D Airflow",
    slug: "corsair-4000d-airflow",
    shortDescription: "Mid-Tower ATX Case High Airflow",
    price: 9999,
    compareAtPrice: 11999,
    brand: "Corsair",
    model: "4000D Airflow",
    category: "pc-cases",
    tags: ["gaming", "atx"],
    badges: ["value-pick"],
    specs: [
      { key: "Form Factor", value: "Mid-Tower" },
      { key: "Motherboard Support", value: "ATX, Micro-ATX, Mini-ITX" },
      { key: "GPU Clearance", value: "360mm" },
    ],
  },
  {
    name: "Fractal Design North",
    slug: "fractal-design-north",
    shortDescription: "Mid-Tower ATX Premium Case",
    price: 14999,
    brand: "Fractal Design",
    model: "North",
    category: "pc-cases",
    tags: ["premium", "silent"],
    badges: ["editors-choice"],
    specs: [
      { key: "Form Factor", value: "Mid-Tower" },
      { key: "Material", value: "Wood + Steel + TG" },
      { key: "GPU Clearance", value: "355mm" },
    ],
  },
  {
    name: "Cooler Master NR200P Max",
    slug: "cooler-master-nr200p-max",
    shortDescription: "Mini-ITX SFF Case with AIO & PSU",
    price: 24999,
    brand: "Cooler Master",
    model: "NR200P Max",
    category: "pc-cases",
    tags: ["mini-itx", "compact"],
    badges: ["premium"],
    specs: [
      { key: "Form Factor", value: "Mini-ITX" },
      { key: "GPU Clearance", value: "336mm" },
      { key: "Included", value: "280mm AIO + 850W SFX PSU" },
    ],
  },
  {
    name: "Ant Esports ICE-511MT",
    slug: "ant-esports-ice-511mt",
    shortDescription: "Mid-Tower ATX Gaming Case with ARGB",
    price: 3999,
    brand: "Ant Esports",
    model: "ICE-511MT",
    category: "pc-cases",
    tags: ["budget", "rgb"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Form Factor", value: "Mid-Tower" },
      { key: "Motherboard Support", value: "ATX, Micro-ATX" },
      { key: "Fans Included", value: "4x ARGB" },
    ],
  },
];

// ==================== CPU COOLERS ====================
export const cpuCoolers: ProductData[] = [
  {
    name: "NZXT Kraken X73 RGB 360mm AIO",
    slug: "nzxt-kraken-x73-rgb",
    shortDescription: "360mm RGB AIO Liquid Cooler",
    price: 18999,
    compareAtPrice: 21999,
    brand: "NZXT",
    model: "Kraken X73 RGB",
    category: "cpu-coolers",
    isFeatured: true,
    tags: ["gaming", "rgb"],
    badges: ["best-seller"],
    specs: [
      { key: "Radiator Size", value: "360mm" },
      { key: "Fan Speed", value: "500-2000 RPM" },
      { key: "Noise Level", value: "21-36 dBA" },
      { key: "RGB", value: "Yes - Infinity Mirror" },
    ],
  },
  {
    name: "Corsair iCUE H150i Elite LCD",
    slug: "corsair-icue-h150i-elite-lcd",
    shortDescription: "360mm AIO with LCD Display",
    price: 24999,
    brand: "Corsair",
    model: "iCUE H150i Elite LCD",
    category: "cpu-coolers",
    tags: ["premium", "rgb"],
    badges: ["premium"],
    specs: [
      { key: "Radiator Size", value: "360mm" },
      { key: "Display", value: "2.1\" IPS LCD" },
      { key: "Fans", value: "3x ML120 RGB" },
    ],
  },
  {
    name: "Deepcool AK620",
    slug: "deepcool-ak620",
    shortDescription: "Dual Tower Air Cooler",
    price: 5999,
    compareAtPrice: 6999,
    brand: "Deepcool",
    model: "AK620",
    category: "cpu-coolers",
    tags: ["silent"],
    badges: ["value-pick"],
    specs: [
      { key: "Type", value: "Dual Tower Air Cooler" },
      { key: "TDP", value: "260W" },
      { key: "Height", value: "160mm" },
      { key: "Fans", value: "2x 120mm" },
    ],
  },
  {
    name: "Noctua NH-D15",
    slug: "noctua-nh-d15",
    shortDescription: "Premium Dual Tower Air Cooler",
    price: 9999,
    brand: "Noctua",
    model: "NH-D15",
    category: "cpu-coolers",
    tags: ["silent", "premium"],
    badges: ["editors-choice"],
    specs: [
      { key: "Type", value: "Dual Tower Air Cooler" },
      { key: "TDP", value: "250W+" },
      { key: "Height", value: "165mm" },
      { key: "Noise Level", value: "24.6 dBA" },
    ],
  },
  {
    name: "Cooler Master Hyper 212 RGB",
    slug: "cooler-master-hyper-212-rgb",
    shortDescription: "Tower Air Cooler with RGB Fan",
    price: 3499,
    brand: "Cooler Master",
    model: "Hyper 212 RGB",
    category: "cpu-coolers",
    tags: ["budget", "rgb"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Type", value: "Tower Air Cooler" },
      { key: "TDP", value: "150W" },
      { key: "Height", value: "159mm" },
    ],
  },
];

// Export all products combined
export const allProducts: ProductData[] = [
  ...processors,
  ...graphicsCards,
  ...motherboards,
  ...ram,
  ...storage,
  ...powerSupplies,
  ...pcCases,
  ...cpuCoolers,
];
