// Peripherals and other products data

import { ProductData } from "./products";

// ==================== KEYBOARDS ====================
export const keyboards: ProductData[] = [
  {
    name: "Logitech G Pro X Mechanical",
    slug: "logitech-g-pro-x-mechanical",
    shortDescription: "TKL Mechanical Gaming Keyboard",
    price: 12999,
    compareAtPrice: 14999,
    brand: "Logitech",
    model: "G Pro X",
    category: "keyboards",
    isFeatured: true,
    tags: ["gaming", "mechanical", "rgb"],
    badges: ["best-seller"],
    specs: [
      { key: "Type", value: "Mechanical" },
      { key: "Layout", value: "TKL (Tenkeyless)" },
      { key: "Switches", value: "Hot-swappable GX" },
      { key: "Backlight", value: "RGB" },
      { key: "Connection", value: "USB-C Detachable" },
    ],
  },
  {
    name: "Razer BlackWidow V4 Pro",
    slug: "razer-blackwidow-v4-pro",
    shortDescription: "Full Size Mechanical Gaming Keyboard",
    price: 22999,
    brand: "Razer",
    model: "BlackWidow V4 Pro",
    category: "keyboards",
    tags: ["gaming", "mechanical", "rgb"],
    badges: ["premium"],
    specs: [
      { key: "Type", value: "Mechanical" },
      { key: "Switches", value: "Razer Green/Yellow" },
      { key: "Layout", value: "Full Size" },
      { key: "Features", value: "Command Dial, Media Keys" },
    ],
  },
  {
    name: "Corsair K70 RGB Pro",
    slug: "corsair-k70-rgb-pro",
    shortDescription: "Full Size Cherry MX Keyboard",
    price: 14999,
    compareAtPrice: 16999,
    brand: "Corsair",
    model: "K70 RGB Pro",
    category: "keyboards",
    tags: ["gaming", "mechanical", "rgb"],
    badges: ["trending"],
    specs: [
      { key: "Switches", value: "Cherry MX Red" },
      { key: "Layout", value: "Full Size" },
      { key: "Frame", value: "Aluminum" },
    ],
  },
  {
    name: "Keychron K8 Pro",
    slug: "keychron-k8-pro",
    shortDescription: "TKL Wireless Mechanical Keyboard",
    price: 9999,
    brand: "Keychron",
    model: "K8 Pro",
    category: "keyboards",
    tags: ["mechanical", "wireless"],
    badges: ["value-pick"],
    specs: [
      { key: "Type", value: "Mechanical Hot-swappable" },
      { key: "Layout", value: "TKL" },
      { key: "Connection", value: "Bluetooth 5.1 + USB-C" },
      { key: "Battery", value: "4000mAh" },
    ],
  },
  {
    name: "HyperX Alloy Origins Core",
    slug: "hyperx-alloy-origins-core",
    shortDescription: "TKL RGB Mechanical Keyboard",
    price: 7999,
    brand: "HyperX",
    model: "Alloy Origins Core",
    category: "keyboards",
    tags: ["gaming", "mechanical"],
    specs: [
      { key: "Switches", value: "HyperX Red" },
      { key: "Layout", value: "TKL" },
      { key: "Frame", value: "Aircraft Aluminum" },
    ],
  },
  {
    name: "Logitech K380 Multi-Device",
    slug: "logitech-k380-multi-device",
    shortDescription: "Compact Bluetooth Keyboard",
    price: 2999,
    brand: "Logitech",
    model: "K380",
    category: "keyboards",
    tags: ["office", "wireless", "compact"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Type", value: "Membrane" },
      { key: "Connection", value: "Bluetooth" },
      { key: "Multi-Device", value: "3 Devices" },
      { key: "Battery", value: "2 Years (AAA)" },
    ],
  },
  {
    name: "TVS Gold Mechanical Keyboard",
    slug: "tvs-gold-mechanical",
    shortDescription: "Classic Mechanical Keyboard",
    price: 4499,
    brand: "TVS",
    model: "Gold Bharat",
    category: "keyboards",
    tags: ["mechanical", "office"],
    specs: [
      { key: "Type", value: "Mechanical" },
      { key: "Layout", value: "Full Size" },
      { key: "Switch", value: "Cherry MX Blue Equivalent" },
    ],
  },
];

// ==================== MICE ====================
export const mice: ProductData[] = [
  {
    name: "Logitech G Pro X Superlight 2",
    slug: "logitech-g-pro-x-superlight-2",
    shortDescription: "Ultra-Lightweight Wireless Gaming Mouse",
    price: 14999,
    compareAtPrice: 16999,
    brand: "Logitech",
    model: "G Pro X Superlight 2",
    category: "mice",
    isFeatured: true,
    tags: ["gaming", "wireless"],
    badges: ["best-seller", "new-arrival"],
    specs: [
      { key: "Sensor", value: "HERO 2" },
      { key: "DPI", value: "32,000" },
      { key: "Weight", value: "60g" },
      { key: "Battery", value: "95 Hours" },
    ],
  },
  {
    name: "Razer DeathAdder V3 Pro",
    slug: "razer-deathadder-v3-pro",
    shortDescription: "Ergonomic Wireless Gaming Mouse",
    price: 12999,
    brand: "Razer",
    model: "DeathAdder V3 Pro",
    category: "mice",
    tags: ["gaming", "wireless"],
    badges: ["trending"],
    specs: [
      { key: "Sensor", value: "Focus Pro 30K" },
      { key: "DPI", value: "30,000" },
      { key: "Weight", value: "63g" },
      { key: "Battery", value: "90 Hours" },
    ],
  },
  {
    name: "SteelSeries Aerox 3 Wireless",
    slug: "steelseries-aerox-3-wireless",
    shortDescription: "Ultra-Lightweight Wireless Mouse",
    price: 9999,
    brand: "SteelSeries",
    model: "Aerox 3 Wireless",
    category: "mice",
    tags: ["gaming", "wireless"],
    specs: [
      { key: "Sensor", value: "TrueMove Air" },
      { key: "DPI", value: "18,000" },
      { key: "Weight", value: "68g" },
      { key: "Battery", value: "200 Hours" },
    ],
  },
  {
    name: "Logitech G502 Hero",
    slug: "logitech-g502-hero",
    shortDescription: "High Performance Gaming Mouse",
    price: 4999,
    compareAtPrice: 5999,
    brand: "Logitech",
    model: "G502 Hero",
    category: "mice",
    tags: ["gaming", "rgb"],
    badges: ["value-pick"],
    specs: [
      { key: "Sensor", value: "HERO 25K" },
      { key: "DPI", value: "25,600" },
      { key: "Weight", value: "121g (adjustable)" },
      { key: "Buttons", value: "11 Programmable" },
    ],
  },
  {
    name: "Razer Viper Mini",
    slug: "razer-viper-mini",
    shortDescription: "Lightweight Ambidextrous Gaming Mouse",
    price: 2999,
    brand: "Razer",
    model: "Viper Mini",
    category: "mice",
    tags: ["gaming", "budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Sensor", value: "8500 DPI Optical" },
      { key: "Weight", value: "61g" },
      { key: "Buttons", value: "6" },
    ],
  },
  {
    name: "Logitech MX Master 3S",
    slug: "logitech-mx-master-3s",
    shortDescription: "Wireless Productivity Mouse",
    price: 9999,
    brand: "Logitech",
    model: "MX Master 3S",
    category: "mice",
    tags: ["office", "wireless"],
    badges: ["editors-choice"],
    specs: [
      { key: "Sensor", value: "8000 DPI" },
      { key: "Battery", value: "70 Days" },
      { key: "Connection", value: "Bluetooth + USB Receiver" },
      { key: "Multi-Device", value: "3 Devices" },
    ],
  },
  {
    name: "Logitech M240 Silent",
    slug: "logitech-m240-silent",
    shortDescription: "Silent Wireless Mouse",
    price: 1299,
    brand: "Logitech",
    model: "M240 Silent",
    category: "mice",
    tags: ["office", "wireless", "silent"],
    specs: [
      { key: "Connection", value: "Bluetooth" },
      { key: "Battery", value: "18 Months" },
      { key: "Silent Clicks", value: "Yes" },
    ],
  },
];

// ==================== MOUSE PADS ====================
export const mousePads: ProductData[] = [
  {
    name: "SteelSeries QcK Heavy XXL",
    slug: "steelseries-qck-heavy-xxl",
    shortDescription: "Extra Large Gaming Mouse Pad",
    price: 3499,
    brand: "SteelSeries",
    model: "QcK Heavy XXL",
    category: "mouse-pads",
    tags: ["gaming"],
    badges: ["best-seller"],
    specs: [
      { key: "Size", value: "900 x 400 x 6mm" },
      { key: "Material", value: "Cloth" },
      { key: "Base", value: "Rubber" },
    ],
  },
  {
    name: "Razer Goliathus Extended Chroma",
    slug: "razer-goliathus-extended-chroma",
    shortDescription: "RGB Extended Gaming Mouse Pad",
    price: 4999,
    brand: "Razer",
    model: "Goliathus Extended Chroma",
    category: "mouse-pads",
    tags: ["gaming", "rgb"],
    specs: [
      { key: "Size", value: "920 x 294 x 3mm" },
      { key: "RGB", value: "Yes" },
      { key: "Surface", value: "Micro-textured Cloth" },
    ],
  },
  {
    name: "Logitech G640",
    slug: "logitech-g640",
    shortDescription: "Large Cloth Gaming Mouse Pad",
    price: 2499,
    brand: "Logitech",
    model: "G640",
    category: "mouse-pads",
    tags: ["gaming"],
    specs: [
      { key: "Size", value: "460 x 400 x 3mm" },
      { key: "Surface", value: "Moderate Surface Friction" },
    ],
  },
  {
    name: "Corsair MM300 Extended",
    slug: "corsair-mm300-extended",
    shortDescription: "Extended Gaming Mouse Pad",
    price: 2999,
    brand: "Corsair",
    model: "MM300 Extended",
    category: "mouse-pads",
    tags: ["gaming"],
    badges: ["value-pick"],
    specs: [
      { key: "Size", value: "930 x 300 x 3mm" },
      { key: "Material", value: "Cloth" },
      { key: "Edge", value: "Anti-Fray Stitched" },
    ],
  },
];

// ==================== MONITORS ====================
export const monitors: ProductData[] = [
  {
    name: "ASUS ROG Swift PG27AQN",
    slug: "asus-rog-swift-pg27aqn",
    shortDescription: "27\" 1440p 360Hz Gaming Monitor",
    price: 89999,
    brand: "ASUS",
    model: "ROG Swift PG27AQN",
    category: "monitors",
    isFeatured: true,
    tags: ["gaming", "4k", "240hz"],
    badges: ["premium"],
    specs: [
      { key: "Size", value: "27 inch" },
      { key: "Resolution", value: "2560 x 1440" },
      { key: "Refresh Rate", value: "360Hz" },
      { key: "Panel", value: "IPS" },
      { key: "Response Time", value: "1ms GTG" },
    ],
  },
  {
    name: "LG 27GP850-B UltraGear",
    slug: "lg-27gp850-b-ultragear",
    shortDescription: "27\" 1440p 165Hz Nano IPS Gaming Monitor",
    price: 34999,
    compareAtPrice: 39999,
    brand: "LG",
    model: "27GP850-B",
    category: "monitors",
    tags: ["gaming", "144hz"],
    badges: ["best-seller"],
    specs: [
      { key: "Size", value: "27 inch" },
      { key: "Resolution", value: "2560 x 1440" },
      { key: "Refresh Rate", value: "165Hz (OC 180Hz)" },
      { key: "Panel", value: "Nano IPS" },
      { key: "Response Time", value: "1ms GTG" },
    ],
  },
  {
    name: "Samsung Odyssey G7 32\"",
    slug: "samsung-odyssey-g7-32",
    shortDescription: "32\" 1440p 240Hz Curved Gaming Monitor",
    price: 49999,
    brand: "Samsung",
    model: "Odyssey G7",
    category: "monitors",
    tags: ["gaming", "240hz"],
    badges: ["trending"],
    specs: [
      { key: "Size", value: "32 inch" },
      { key: "Resolution", value: "2560 x 1440" },
      { key: "Refresh Rate", value: "240Hz" },
      { key: "Panel", value: "VA" },
      { key: "Curve", value: "1000R" },
    ],
  },
  {
    name: "Dell S2722QC 4K",
    slug: "dell-s2722qc-4k",
    shortDescription: "27\" 4K USB-C IPS Monitor",
    price: 34999,
    brand: "Dell",
    model: "S2722QC",
    category: "monitors",
    tags: ["4k", "office"],
    badges: ["value-pick"],
    specs: [
      { key: "Size", value: "27 inch" },
      { key: "Resolution", value: "3840 x 2160 (4K)" },
      { key: "Panel", value: "IPS" },
      { key: "USB-C", value: "65W Power Delivery" },
    ],
  },
  {
    name: "BenQ MOBIUZ EX2710S",
    slug: "benq-mobiuz-ex2710s",
    shortDescription: "27\" 1080p 165Hz Gaming Monitor",
    price: 21999,
    brand: "BenQ",
    model: "MOBIUZ EX2710S",
    category: "monitors",
    tags: ["gaming", "144hz"],
    specs: [
      { key: "Size", value: "27 inch" },
      { key: "Resolution", value: "1920 x 1080" },
      { key: "Refresh Rate", value: "165Hz" },
      { key: "Panel", value: "IPS" },
      { key: "HDRi", value: "Yes" },
    ],
  },
  {
    name: "Acer Nitro XV240Y",
    slug: "acer-nitro-xv240y",
    shortDescription: "24\" 1080p 165Hz IPS Gaming Monitor",
    price: 14999,
    brand: "Acer",
    model: "Nitro XV240Y",
    category: "monitors",
    tags: ["gaming", "144hz", "budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Size", value: "23.8 inch" },
      { key: "Resolution", value: "1920 x 1080" },
      { key: "Refresh Rate", value: "165Hz" },
      { key: "Panel", value: "IPS" },
    ],
  },
  {
    name: "LG 24MK430H",
    slug: "lg-24mk430h",
    shortDescription: "24\" FHD IPS Monitor",
    price: 9499,
    brand: "LG",
    model: "24MK430H",
    category: "monitors",
    tags: ["office", "budget"],
    specs: [
      { key: "Size", value: "24 inch" },
      { key: "Resolution", value: "1920 x 1080" },
      { key: "Panel", value: "IPS" },
      { key: "Refresh Rate", value: "75Hz" },
    ],
  },
];

// ==================== WEBCAMS ====================
export const webcams: ProductData[] = [
  {
    name: "Logitech C920 HD Pro",
    slug: "logitech-c920-hd-pro",
    shortDescription: "1080p HD Webcam with Stereo Audio",
    price: 7999,
    brand: "Logitech",
    model: "C920 HD Pro",
    category: "webcams",
    tags: ["office"],
    badges: ["best-seller"],
    specs: [
      { key: "Resolution", value: "1080p/30fps" },
      { key: "Microphone", value: "Dual Stereo" },
      { key: "Autofocus", value: "Yes" },
    ],
  },
  {
    name: "Logitech Brio 4K",
    slug: "logitech-brio-4k",
    shortDescription: "4K Ultra HD Webcam",
    price: 18999,
    brand: "Logitech",
    model: "Brio 4K",
    category: "webcams",
    tags: ["premium", "4k"],
    badges: ["premium"],
    specs: [
      { key: "Resolution", value: "4K/30fps, 1080p/60fps" },
      { key: "HDR", value: "Yes" },
      { key: "Windows Hello", value: "Supported" },
    ],
  },
  {
    name: "Razer Kiyo Pro",
    slug: "razer-kiyo-pro",
    shortDescription: "1080p 60fps Streaming Webcam",
    price: 14999,
    brand: "Razer",
    model: "Kiyo Pro",
    category: "webcams",
    tags: ["gaming"],
    specs: [
      { key: "Resolution", value: "1080p/60fps" },
      { key: "Sensor", value: "Sony STARVIS" },
      { key: "FOV", value: "Adjustable" },
    ],
  },
  {
    name: "Logitech C310",
    slug: "logitech-c310",
    shortDescription: "HD 720p Webcam",
    price: 2499,
    brand: "Logitech",
    model: "C310",
    category: "webcams",
    tags: ["budget", "office"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Resolution", value: "720p/30fps" },
      { key: "Microphone", value: "Mono" },
    ],
  },
];

// ==================== HEADPHONES & AUDIO ====================
export const audio: ProductData[] = [
  {
    name: "HyperX Cloud III",
    slug: "hyperx-cloud-iii",
    shortDescription: "Gaming Headset with DTS:X Spatial Audio",
    price: 9999,
    compareAtPrice: 11999,
    brand: "HyperX",
    model: "Cloud III",
    category: "gaming-headsets",
    isFeatured: true,
    tags: ["gaming"],
    badges: ["best-seller"],
    specs: [
      { key: "Drivers", value: "53mm" },
      { key: "Frequency", value: "10Hz-21kHz" },
      { key: "Microphone", value: "Detachable" },
      { key: "Connection", value: "3.5mm + USB" },
    ],
  },
  {
    name: "SteelSeries Arctis Nova Pro Wireless",
    slug: "steelseries-arctis-nova-pro-wireless",
    shortDescription: "Premium Wireless Gaming Headset",
    price: 34999,
    brand: "SteelSeries",
    model: "Arctis Nova Pro Wireless",
    category: "gaming-headsets",
    tags: ["gaming", "wireless", "premium"],
    badges: ["premium"],
    specs: [
      { key: "Drivers", value: "40mm" },
      { key: "Active Noise Cancellation", value: "Yes" },
      { key: "Battery", value: "Dual Hot-Swap" },
      { key: "Connection", value: "2.4GHz + Bluetooth" },
    ],
  },
  {
    name: "Logitech G Pro X 2 Lightspeed",
    slug: "logitech-g-pro-x-2-lightspeed",
    shortDescription: "Pro-Grade Wireless Gaming Headset",
    price: 22999,
    brand: "Logitech",
    model: "G Pro X 2 Lightspeed",
    category: "gaming-headsets",
    tags: ["gaming", "wireless"],
    badges: ["trending"],
    specs: [
      { key: "Drivers", value: "50mm Graphene" },
      { key: "Battery", value: "50 Hours" },
      { key: "Connection", value: "Lightspeed + Bluetooth + 3.5mm" },
    ],
  },
  {
    name: "JBL Quantum 100",
    slug: "jbl-quantum-100",
    shortDescription: "Wired Gaming Headset",
    price: 2999,
    brand: "JBL",
    model: "Quantum 100",
    category: "gaming-headsets",
    tags: ["gaming", "budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Drivers", value: "40mm" },
      { key: "Connection", value: "3.5mm" },
      { key: "Microphone", value: "Detachable Boom" },
    ],
  },
  {
    name: "Sony WH-1000XM5",
    slug: "sony-wh-1000xm5",
    shortDescription: "Premium Noise Cancelling Headphones",
    price: 29999,
    brand: "Sony",
    model: "WH-1000XM5",
    category: "headphones",
    tags: ["wireless", "premium", "silent"],
    badges: ["editors-choice"],
    specs: [
      { key: "Drivers", value: "30mm" },
      { key: "ANC", value: "Yes - Industry Leading" },
      { key: "Battery", value: "30 Hours" },
      { key: "Connection", value: "Bluetooth 5.2" },
    ],
  },
  {
    name: "boAt Rockerz 450",
    slug: "boat-rockerz-450",
    shortDescription: "Wireless Bluetooth Headphones",
    price: 1499,
    brand: "boAt",
    model: "Rockerz 450",
    category: "headphones",
    tags: ["wireless", "budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Drivers", value: "40mm" },
      { key: "Battery", value: "15 Hours" },
      { key: "Connection", value: "Bluetooth + AUX" },
    ],
  },
  {
    name: "Creative Pebble V3",
    slug: "creative-pebble-v3",
    shortDescription: "USB-C Desktop Speakers",
    price: 3499,
    brand: "Creative",
    model: "Pebble V3",
    category: "speakers",
    tags: ["office"],
    badges: ["value-pick"],
    specs: [
      { key: "Power", value: "8W RMS" },
      { key: "Connection", value: "USB-C + Bluetooth 5.0" },
      { key: "Drivers", value: "2.25 inch" },
    ],
  },
  {
    name: "Logitech Z407",
    slug: "logitech-z407",
    shortDescription: "2.1 Bluetooth Computer Speakers",
    price: 7999,
    brand: "Logitech",
    model: "Z407",
    category: "speakers",
    tags: ["office"],
    specs: [
      { key: "Power", value: "80W Peak" },
      { key: "Configuration", value: "2.1" },
      { key: "Connection", value: "Bluetooth + 3.5mm + USB" },
    ],
  },
];

// ==================== LAPTOPS ====================
export const laptops: ProductData[] = [
  {
    name: "ASUS ROG Strix G16 (2024)",
    slug: "asus-rog-strix-g16-2024",
    shortDescription: "16\" RTX 4070 Gaming Laptop",
    price: 149999,
    compareAtPrice: 164999,
    brand: "ASUS",
    model: "ROG Strix G16",
    category: "gaming-laptops",
    isFeatured: true,
    tags: ["gaming", "high-performance"],
    badges: ["best-seller", "new-arrival"],
    specs: [
      { key: "Processor", value: "Intel Core i9-14900HX" },
      { key: "GPU", value: "NVIDIA RTX 4070 8GB" },
      { key: "RAM", value: "16GB DDR5" },
      { key: "Storage", value: "1TB NVMe SSD" },
      { key: "Display", value: "16\" QHD+ 240Hz" },
    ],
  },
  {
    name: "Lenovo Legion Pro 5",
    slug: "lenovo-legion-pro-5",
    shortDescription: "16\" RTX 4060 Gaming Laptop",
    price: 129999,
    brand: "Lenovo",
    model: "Legion Pro 5",
    category: "gaming-laptops",
    tags: ["gaming"],
    badges: ["trending"],
    specs: [
      { key: "Processor", value: "AMD Ryzen 7 7745HX" },
      { key: "GPU", value: "NVIDIA RTX 4060 8GB" },
      { key: "RAM", value: "16GB DDR5" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "16\" WQXGA 165Hz" },
    ],
  },
  {
    name: "Acer Nitro V 15",
    slug: "acer-nitro-v-15",
    shortDescription: "15.6\" RTX 4050 Budget Gaming Laptop",
    price: 74999,
    compareAtPrice: 84999,
    brand: "Acer",
    model: "Nitro V 15",
    category: "gaming-laptops",
    tags: ["gaming", "budget"],
    badges: ["value-pick"],
    specs: [
      { key: "Processor", value: "Intel Core i5-13420H" },
      { key: "GPU", value: "NVIDIA RTX 4050 6GB" },
      { key: "RAM", value: "8GB DDR5" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "15.6\" FHD 144Hz" },
    ],
  },
  {
    name: "HP Pavilion 15",
    slug: "hp-pavilion-15",
    shortDescription: "15.6\" Student & Work Laptop",
    price: 54999,
    brand: "HP",
    model: "Pavilion 15",
    category: "student-laptops",
    tags: ["office", "budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Processor", value: "AMD Ryzen 5 7530U" },
      { key: "RAM", value: "8GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "15.6\" FHD IPS" },
    ],
  },
  {
    name: "Lenovo IdeaPad Slim 3",
    slug: "lenovo-ideapad-slim-3",
    shortDescription: "15.6\" Everyday Laptop",
    price: 44999,
    brand: "Lenovo",
    model: "IdeaPad Slim 3",
    category: "student-laptops",
    tags: ["office", "budget"],
    specs: [
      { key: "Processor", value: "Intel Core i3-1315U" },
      { key: "RAM", value: "8GB DDR4" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Display", value: "15.6\" FHD" },
    ],
  },
  {
    name: "Dell XPS 15 (2024)",
    slug: "dell-xps-15-2024",
    shortDescription: "15.6\" Premium Ultrabook",
    price: 169999,
    brand: "Dell",
    model: "XPS 15",
    category: "thin-light-laptops",
    tags: ["premium"],
    badges: ["premium"],
    specs: [
      { key: "Processor", value: "Intel Core Ultra 7 155H" },
      { key: "GPU", value: "Intel Arc Graphics" },
      { key: "RAM", value: "16GB DDR5" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "15.6\" 3.5K OLED" },
    ],
  },
  {
    name: "Apple MacBook Air M3",
    slug: "apple-macbook-air-m3",
    shortDescription: "13.6\" M3 Chip Ultrabook",
    price: 114999,
    brand: "Apple",
    model: "MacBook Air M3",
    category: "thin-light-laptops",
    isFeatured: true,
    tags: ["premium"],
    badges: ["editors-choice"],
    specs: [
      { key: "Chip", value: "Apple M3" },
      { key: "RAM", value: "8GB Unified" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Display", value: "13.6\" Liquid Retina" },
      { key: "Battery", value: "18 Hours" },
    ],
  },
  {
    name: "Lenovo ThinkPad E14 Gen 5",
    slug: "lenovo-thinkpad-e14-gen5",
    shortDescription: "14\" Business Laptop",
    price: 69999,
    brand: "Lenovo",
    model: "ThinkPad E14 Gen 5",
    category: "business-laptops",
    tags: ["office"],
    specs: [
      { key: "Processor", value: "Intel Core i5-1335U" },
      { key: "RAM", value: "8GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "14\" FHD IPS" },
    ],
  },
];

// ==================== NETWORKING ====================
export const networking: ProductData[] = [
  {
    name: "TP-Link Archer AX73 WiFi 6 Router",
    slug: "tp-link-archer-ax73",
    shortDescription: "AX5400 Dual Band WiFi 6 Router",
    price: 8999,
    compareAtPrice: 10999,
    brand: "TP-Link",
    model: "Archer AX73",
    category: "routers",
    tags: ["office"],
    badges: ["best-seller"],
    specs: [
      { key: "Speed", value: "5400 Mbps (AX5400)" },
      { key: "WiFi", value: "WiFi 6" },
      { key: "Ports", value: "4x Gigabit LAN + 1x WAN" },
      { key: "Coverage", value: "2500 sq ft" },
    ],
  },
  {
    name: "ASUS RT-AX86U Pro",
    slug: "asus-rt-ax86u-pro",
    shortDescription: "AX5700 Gaming Router",
    price: 24999,
    brand: "ASUS",
    model: "RT-AX86U Pro",
    category: "routers",
    tags: ["gaming"],
    badges: ["premium"],
    specs: [
      { key: "Speed", value: "5700 Mbps" },
      { key: "WiFi", value: "WiFi 6" },
      { key: "2.5G Port", value: "Yes" },
      { key: "Game Boost", value: "Yes" },
    ],
  },
  {
    name: "TP-Link Deco X50 (3-Pack)",
    slug: "tp-link-deco-x50-3pack",
    shortDescription: "AX3000 Mesh WiFi 6 System",
    price: 14999,
    brand: "TP-Link",
    model: "Deco X50",
    category: "routers",
    tags: ["office"],
    badges: ["value-pick"],
    specs: [
      { key: "Speed", value: "3000 Mbps" },
      { key: "Coverage", value: "6500 sq ft" },
      { key: "Units", value: "3" },
    ],
  },
  {
    name: "TP-Link TL-SG108 8-Port Switch",
    slug: "tp-link-tl-sg108",
    shortDescription: "8-Port Gigabit Desktop Switch",
    price: 1999,
    brand: "TP-Link",
    model: "TL-SG108",
    category: "switches",
    specs: [
      { key: "Ports", value: "8x Gigabit" },
      { key: "Type", value: "Unmanaged" },
    ],
  },
  {
    name: "TP-Link Archer T3U Plus",
    slug: "tp-link-archer-t3u-plus",
    shortDescription: "AC1300 USB WiFi Adapter",
    price: 1499,
    brand: "TP-Link",
    model: "Archer T3U Plus",
    category: "wifi-adapters",
    badges: ["budget-friendly"],
    specs: [
      { key: "Speed", value: "1300 Mbps" },
      { key: "USB", value: "USB 3.0" },
      { key: "Antenna", value: "High Gain" },
    ],
  },
  {
    name: "Cat 6 Ethernet Cable 5m",
    slug: "cat6-ethernet-5m",
    shortDescription: "Cat 6 RJ45 Network Cable 5 Meters",
    price: 299,
    brand: "Generic",
    model: "Cat 6",
    category: "ethernet-cables",
    specs: [
      { key: "Length", value: "5 Meters" },
      { key: "Category", value: "Cat 6" },
      { key: "Speed", value: "1 Gbps" },
    ],
  },
];

// ==================== GAMING ACCESSORIES ====================
export const gamingAccessories: ProductData[] = [
  {
    name: "Secretlab TITAN Evo 2022",
    slug: "secretlab-titan-evo-2022",
    shortDescription: "Premium Ergonomic Gaming Chair",
    price: 44999,
    brand: "Secretlab",
    model: "TITAN Evo 2022",
    category: "gaming-chairs",
    isFeatured: true,
    tags: ["gaming", "premium"],
    badges: ["premium", "editors-choice"],
    specs: [
      { key: "Material", value: "NEO Hybrid Leatherette" },
      { key: "Recline", value: "165 degrees" },
      { key: "Armrests", value: "4D" },
      { key: "Lumbar Support", value: "Integrated Adjustable" },
    ],
  },
  {
    name: "Green Soul Monster Ultimate",
    slug: "green-soul-monster-ultimate",
    shortDescription: "Ergonomic Gaming Chair",
    price: 16999,
    compareAtPrice: 19999,
    brand: "Green Soul",
    model: "Monster Ultimate",
    category: "gaming-chairs",
    tags: ["gaming"],
    badges: ["best-seller"],
    specs: [
      { key: "Material", value: "PU Leather" },
      { key: "Recline", value: "180 degrees" },
      { key: "Armrests", value: "3D" },
    ],
  },
  {
    name: "IKEA MARKUS",
    slug: "ikea-markus",
    shortDescription: "Office/Gaming Chair",
    price: 12999,
    brand: "IKEA",
    model: "MARKUS",
    category: "office-chairs",
    tags: ["office"],
    badges: ["value-pick"],
    specs: [
      { key: "Material", value: "Mesh Back" },
      { key: "Adjustable", value: "Height, Tilt" },
    ],
  },
  {
    name: "Xbox Wireless Controller",
    slug: "xbox-wireless-controller",
    shortDescription: "Wireless Game Controller for PC/Xbox",
    price: 5499,
    brand: "Microsoft",
    model: "Xbox Wireless Controller",
    category: "controllers",
    tags: ["gaming"],
    badges: ["best-seller"],
    specs: [
      { key: "Connection", value: "Bluetooth + USB-C" },
      { key: "Compatible", value: "Xbox, PC, Mobile" },
      { key: "Battery", value: "40 Hours (AA)" },
    ],
  },
  {
    name: "Sony DualSense",
    slug: "sony-dualsense",
    shortDescription: "PS5 Wireless Controller",
    price: 5999,
    brand: "Sony",
    model: "DualSense",
    category: "controllers",
    tags: ["gaming"],
    specs: [
      { key: "Features", value: "Haptic Feedback, Adaptive Triggers" },
      { key: "Connection", value: "Bluetooth + USB-C" },
      { key: "Battery", value: "Built-in Rechargeable" },
    ],
  },
  {
    name: "Elgato Stream Deck MK.2",
    slug: "elgato-stream-deck-mk2",
    shortDescription: "15 Key LCD Streaming Controller",
    price: 14999,
    brand: "Elgato",
    model: "Stream Deck MK.2",
    category: "streaming-gear",
    tags: ["gaming"],
    badges: ["editors-choice"],
    specs: [
      { key: "Keys", value: "15 LCD Keys" },
      { key: "Connection", value: "USB-C" },
      { key: "Stand", value: "Adjustable" },
    ],
  },
];

// ==================== OFFICE & POWER ====================
export const officePower: ProductData[] = [
  {
    name: "APC Back-UPS 1100VA",
    slug: "apc-back-ups-1100va",
    shortDescription: "1100VA/660W UPS with AVR",
    price: 7499,
    brand: "APC",
    model: "BX1100C-IN",
    category: "ups",
    tags: ["office"],
    badges: ["best-seller"],
    specs: [
      { key: "Capacity", value: "1100VA / 660W" },
      { key: "Outlets", value: "4" },
      { key: "AVR", value: "Yes" },
      { key: "Battery Backup", value: "~20 min (half load)" },
    ],
  },
  {
    name: "APC Back-UPS 600VA",
    slug: "apc-back-ups-600va",
    shortDescription: "600VA/360W Basic UPS",
    price: 3999,
    brand: "APC",
    model: "BX600C-IN",
    category: "ups",
    tags: ["office", "budget"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Capacity", value: "600VA / 360W" },
      { key: "Outlets", value: "3" },
    ],
  },
  {
    name: "Belkin 8-Socket Surge Protector",
    slug: "belkin-8-socket-surge",
    shortDescription: "8 Socket Surge Protector 2M Cable",
    price: 1999,
    brand: "Belkin",
    model: "Surge Protector",
    category: "surge-protectors",
    specs: [
      { key: "Sockets", value: "8" },
      { key: "Cable Length", value: "2 Meters" },
      { key: "Protection", value: "Surge + Spike" },
    ],
  },
  {
    name: "JETION Laptop Stand",
    slug: "jetion-laptop-stand",
    shortDescription: "Aluminum Adjustable Laptop Stand",
    price: 1299,
    brand: "JETION",
    category: "laptop-stands",
    tags: ["office"],
    badges: ["budget-friendly"],
    specs: [
      { key: "Material", value: "Aluminum Alloy" },
      { key: "Adjustable", value: "Yes" },
      { key: "Compatible", value: "10-17 inch Laptops" },
    ],
  },
  {
    name: "Anker USB-C Hub 7-in-1",
    slug: "anker-usb-c-hub-7in1",
    shortDescription: "USB-C Hub with HDMI, USB-A, SD Card",
    price: 3999,
    brand: "Anker",
    model: "PowerExpand+",
    category: "usb-hubs",
    tags: ["office"],
    badges: ["best-seller"],
    specs: [
      { key: "Ports", value: "HDMI, 2x USB-A, USB-C PD, SD, microSD, Ethernet" },
      { key: "HDMI", value: "4K@30Hz" },
      { key: "Power Delivery", value: "100W Pass-through" },
    ],
  },
];

// Combine all products
export const allPeripheralsAndMore: ProductData[] = [
  ...keyboards,
  ...mice,
  ...mousePads,
  ...monitors,
  ...webcams,
  ...audio,
  ...laptops,
  ...networking,
  ...gamingAccessories,
  ...officePower,
];
